# Generated by Django 2.1.7 on 2019-04-05 15:05

from django.db import migrations
import week3.models


class Migration(migrations.Migration):

    dependencies = [
        ('week3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pttspider',
            name='file_urls',
            field=week3.models.ListField(),
        ),
    ]
