# Generated by Django 2.1.7 on 2019-02-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
