# Generated by Django 2.1.7 on 2019-03-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_lists_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='tags',
        ),
    ]
