# Generated by Django 2.1.7 on 2019-03-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_lists_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
