# Generated by Django 2.1.7 on 2019-03-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='to',
            field=models.EmailField(max_length=254),
        ),
    ]
