# Generated by Django 2.1.7 on 2019-03-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('week2', '0002_auto_20190303_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
